name: "flutterwave"
description: "A package to integrate Flutterwave payment into flutter applications"
version: 0.0.1
author: "Flutterwave Developers"
homepage: "https://github.com/Flutterwave/flutterwave-flutter"

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.2
  tripledes: ^2.1.0
  hexcolor: ^1.0.4
  webview_flutter: ^0.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: 4.1.0
flutter:
